version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=local
      - DB_USER=root
      - DB_PASS=root
      - LANGUAGE_CODE=es-es
      - TZ=Europe/Madrid
    networks:
      - seth-network
    depends_on:
      - postgres
  postgres:
      image: postgres:11.2-alpine
      restart: always

      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=local
      ports:
        - "3333:5432"
      networks:
        - seth-network
  ####################################################################################################
  #                                             VOLUMES                                              #
  ####################################################################################################



  ####################################################################################################
  #                                             NETWORKS                                             #
  ####################################################################################################
networks:
  seth-network:
    driver: bridge